// 55+ realistic corporate-IT ticket scenarios.
// ageHours   = how long ago the ticket was created
// resolveAfterHours = time from creation to resolution (omit for still-open tickets)
// status     = final status to leave the ticket in
// assign     = index into TECHNICIANS (omit to leave unassigned)
// csat       = 1..5 (only applied when status is RESOLVED/CLOSED)

export const TICKET_SCENARIOS = [
  // ── Company / department-wide incidents ────────────────────────────
  {
    title: 'Company-wide outage — authentication service down, no one can log in',
    description:
      'The central identity provider is unresponsive. Staff across every site are unable to sign in to email, VPN, the ERP or any SSO application. Complete work stoppage.',
    category: 'Security',
    impact: 'ENTIRE_COMPANY',
    urgency: 'SYSTEM_DOWN',
    status: 'IN_PROGRESS',
    ageHours: 2,
    assign: 0,
    comments: [
      { staff: true, body: 'Major incident declared. Primary IdP node is in a crash loop after the certificate rotation. Failing over to the secondary.' },
      { staff: true, body: 'Secondary IdP is serving auth. Watching error rates before calling it resolved.' },
    ],
    actions: [
      { type: 'ESCALATED', notes: 'Paged the on-call platform engineer and opened the major-incident bridge' },
      { type: 'NETWORK_DIAGNOSTIC', notes: 'IdP health check — primary returning 503, secondary healthy' },
    ],
  },
  {
    title: 'Data centre cooling failure took all hosted services offline',
    description:
      'A cooling unit in the primary server room failed overnight and hosts shut down on thermal protection. Every internally hosted system was unavailable company-wide until hardware was brought back up.',
    category: 'Network',
    impact: 'ENTIRE_COMPANY',
    urgency: 'SYSTEM_DOWN',
    status: 'RESOLVED',
    ageHours: 620,
    resolveAfterHours: 4,
    assign: 0,
    csat: 4,
    comments: [
      { staff: true, body: 'Facilities restored cooling. Bringing hosts up in dependency order: storage, DCs, then application tiers.' },
      { staff: true, body: 'All services back and verified. Post-incident review scheduled; adding a redundant cooling alert.' },
    ],
    actions: [{ type: 'ESCALATED', notes: 'Engaged facilities and the DC vendor; ran the DR bring-up runbook' }],
  },
  {
    title: 'Email delivery delayed company-wide — messages queuing 20+ minutes',
    description:
      'Inbound and outbound mail is delayed across all departments. Users report messages taking 20–40 minutes. Queue depth on the edge transport is climbing.',
    category: 'Email',
    impact: 'ENTIRE_COMPANY',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 220,
    resolveAfterHours: 3,
    assign: 0,
    csat: 4,
    comments: [
      { staff: true, body: 'Confirmed a stuck categorizer thread on transport node 2. Restarting the service.' },
      { staff: true, body: 'Queues draining, delivery back under 1 minute. Monitoring for an hour before closing.' },
    ],
    actions: [{ type: 'NETWORK_DIAGNOSTIC', notes: 'SMTP queue analysis on both transport nodes' }],
  },
  {
    title: 'Core switch failure — 4th floor Engineering offline',
    description:
      'Entire 4th floor lost network connectivity. No DHCP, no wired or wireless. Suspect the access-layer stack.',
    category: 'Network',
    impact: 'DEPARTMENT',
    urgency: 'SYSTEM_DOWN',
    status: 'RESOLVED',
    ageHours: 480,
    resolveAfterHours: 2,
    assign: 3,
    csat: 5,
    comments: [{ staff: true, body: 'Master switch in the stack failed. Promoted the backup and swapped the unit from spares.' }],
    actions: [
      { type: 'NETWORK_DIAGNOSTIC', notes: 'Stack health check — member 1 not responding' },
      { type: 'HARDWARE_SWAP', notes: 'Replaced stack member 1 from the spare pool' },
    ],
  },
  {
    title: 'ERP system unreachable for Finance — month-end close blocked',
    description:
      'Finance cannot reach the ERP web front end. Login page times out. Month-end close is due tomorrow so this is time-critical for the team.',
    category: 'Software',
    impact: 'DEPARTMENT',
    urgency: 'SYSTEM_DOWN',
    status: 'RESOLVED',
    ageHours: 96,
    resolveAfterHours: 4,
    assign: 1,
    csat: 4,
    comments: [{ staff: true, body: 'App pool had crashed after the overnight patch. Recycled and added a health-check alert.' }],
  },
  {
    title: 'Payroll deadline at risk — shared Finance drive read-only for all users',
    description:
      'The entire Finance department share has gone read-only. Nobody can save. Payroll run is this afternoon.',
    category: 'Storage / File Share',
    impact: 'DEPARTMENT',
    urgency: 'SYSTEM_DOWN',
    status: 'CLOSED',
    ageHours: 700,
    resolveAfterHours: 1,
    assign: 2,
    csat: 5,
  },

  // ── VPN cluster (recurring — should trip Problem detection) ─────────
  {
    title: 'VPN connection failing from Calgary remote office after firewall update',
    description:
      'Since the firewall update the VPN tunnel from the Calgary office drops every few minutes. Reconnects then drops again. Affects everyone working from that site.',
    category: 'VPN / Remote Access',
    impact: 'DEPARTMENT',
    urgency: 'WORK_DEGRADED',
    status: 'IN_PROGRESS',
    ageHours: 5,
    assign: 0,
    comments: [{ staff: true, body: 'Seeing the same MTU/fragmentation pattern as the other Calgary reports. Linking these together.' }],
  },
  {
    title: 'VPN keeps disconnecting from home after the firewall change this week',
    description:
      'Working from home in Calgary, the VPN drops roughly every 3 minutes since the firewall change. Have to reconnect constantly to keep working.',
    category: 'VPN / Remote Access',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'OPEN',
    ageHours: 4,
  },
  {
    title: 'Remote access VPN unstable since firewall update — frequent drops',
    description:
      'VPN tunnel from my home network in Calgary will not stay up after the firewall update. Constant disconnects, maybe 3-4 times every ten minutes.',
    category: 'VPN / Remote Access',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'OPEN',
    ageHours: 3,
  },
  {
    title: 'Cannot stay connected to VPN after firewall update — Calgary field staff',
    description:
      'Several field operations staff based out of Calgary report the VPN disconnects repeatedly following the firewall update. Workaround of lowering MTU helps some users.',
    category: 'VPN / Remote Access',
    impact: 'DEPARTMENT',
    urgency: 'WORK_DEGRADED',
    status: 'OPEN',
    ageHours: 2,
  },

  // ── AD lockout cluster (recurring — should trip Problem detection) ──
  {
    title: 'Active Directory account locked out after 3 invalid login attempts',
    description:
      'My account keeps getting locked out. I sign in fine, then 10 minutes later I am locked again. Have not changed my password recently.',
    category: 'Active Directory',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 6,
    resolveAfterHours: 1,
    assign: 4,
    csat: 5,
    comments: [{ staff: true, body: 'Event 4740 points to an old session on a meeting-room PC. Cleared it and unlocked.' }],
    actions: [{ type: 'ACCOUNT_UNLOCK', notes: 'Unlocked after clearing stale RDP session on room PC' }],
  },
  {
    title: 'Repeated AD account lockouts after invalid login attempts this morning',
    description:
      'Account locked three times since 9am. Each time it unlocks after a while and then locks again after a few invalid attempts I am not making.',
    category: 'Active Directory',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'IN_PROGRESS',
    ageHours: 5,
    assign: 4,
  },
  {
    title: 'AD account keeps locking out — invalid login attempts from unknown source',
    description:
      'Getting locked out of Active Directory repeatedly. IT said it is invalid login attempts but I only ever type my password once. Started this morning.',
    category: 'Active Directory',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'OPEN',
    ageHours: 4,
  },
  {
    title: 'Account lockout loop — invalid login attempts, cannot stay signed in',
    description:
      'My Active Directory account goes into a lockout loop. Unlock, works for a bit, then invalid login attempts lock it again. Several colleagues have the same today.',
    category: 'Active Directory',
    impact: 'DEPARTMENT',
    urgency: 'WORK_DEGRADED',
    status: 'OPEN',
    ageHours: 3,
  },

  // ── Email / Outlook ───────────────────────────────────────────────
  {
    title: 'Outlook integration breaking on macOS Sequoia endpoints',
    description:
      'After updating to macOS Sequoia, New Outlook will not show shared calendars and add-ins fail to load. Multiple Mac users in Marketing affected.',
    category: 'Email',
    impact: 'DEPARTMENT',
    urgency: 'WORK_DEGRADED',
    status: 'IN_PROGRESS',
    ageHours: 30,
    assign: 1,
    comments: [{ staff: true, body: 'Falling back to Legacy Outlook resolves it. Drafting a KB and checking the fixed build number.' }],
  },
  {
    title: 'Cannot send email — attachment size limit hit on 30 MB deck',
    description: 'Trying to send a 30 MB presentation to a client and it bounces back as too large.',
    category: 'Email',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'RESOLVED',
    ageHours: 60,
    resolveAfterHours: 2,
    assign: 2,
    csat: 4,
    comments: [{ staff: true, body: 'Shared a secure file-share link method. Attachment cap stays at 25 MB by policy.' }],
  },
  {
    title: 'Distribution list "All-Sales" not receiving external emails',
    description: 'Customers emailing all-sales@ get no response. Internal mail to the list works fine.',
    category: 'Email',
    impact: 'DEPARTMENT',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 140,
    resolveAfterHours: 5,
    assign: 0,
    csat: 5,
  },
  {
    title: 'Shared mailbox "Support Intake" missing from Outlook after migration',
    description: 'The Support Intake shared mailbox disappeared from my Outlook profile after the weekend migration.',
    category: 'Email',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'CLOSED',
    ageHours: 300,
    resolveAfterHours: 3,
    assign: 3,
    csat: 4,
  },
  {
    title: 'Phishing email reported — finance-themed invoice with link',
    description:
      'Received a suspicious invoice email asking to confirm bank details via a link. Reporting it and did not click.',
    category: 'Security',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'RESOLVED',
    ageHours: 48,
    resolveAfterHours: 1,
    assign: 4,
    csat: 5,
    comments: [{ staff: true, body: 'Confirmed malicious, purged from all mailboxes, blocked the sender domain and URL.' }],
  },

  // ── Printing ──────────────────────────────────────────────────────
  {
    title: 'Printer offline on 3rd floor — jobs stuck in queue',
    description: 'The main 3rd floor MFP shows offline and everyone\'s print jobs are stuck. Panel shows a network error.',
    category: 'Printing',
    impact: 'DEPARTMENT',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 72,
    resolveAfterHours: 1,
    assign: 3,
    csat: 4,
    actions: [{ type: 'NETWORK_DIAGNOSTIC', notes: 'Printer not pingable; switch port had errdisabled — cleared' }],
  },
  {
    title: 'Scan-to-email failing on 2nd floor MFP after firmware update',
    description: 'Since the firmware update the 2nd floor printer will not scan to email. Printing still works.',
    category: 'Printing',
    impact: 'DEPARTMENT',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'IN_PROGRESS',
    ageHours: 20,
    assign: 3,
  },
  {
    title: 'New print driver push causing "spooler stopped" on Windows 11 laptops',
    description: 'After the driver package update several Windows 11 laptops show the print spooler crashing repeatedly.',
    category: 'Printing',
    impact: 'DEPARTMENT',
    urgency: 'WORK_DEGRADED',
    status: 'OPEN',
    ageHours: 8,
  },
  {
    title: 'Badge/secure print release not working at reception printer',
    description: 'Tapping my badge at the reception printer does nothing. Have to release jobs from the web portal instead.',
    category: 'Printing',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'RESOLVED',
    ageHours: 190,
    resolveAfterHours: 6,
    assign: 3,
    csat: 3,
  },

  // ── Hardware ──────────────────────────────────────────────────────
  {
    title: 'Laptop will not power on — no lights, no fan',
    description: 'My laptop is completely dead this morning. Tried a different charger and wall socket, nothing.',
    category: 'Hardware',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 120,
    resolveAfterHours: 26,
    assign: 2,
    csat: 4,
    actions: [
      { type: 'HARDWARE_SWAP', notes: 'Motherboard fault confirmed by diagnostics; issued loaner then warranty unit' },
    ],
  },
  {
    title: 'Docking station not detecting external monitors after Windows update',
    description: 'Since the latest Windows update my dock will not drive either external monitor. USB devices on the dock still work.',
    category: 'Hardware',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 54,
    resolveAfterHours: 3,
    assign: 1,
    csat: 4,
    comments: [{ staff: true, body: 'Rolled back the DisplayLink driver to the known-good version and pinned it.' }],
  },
  {
    title: 'Keyboard keys sticking on ThinkPad — several keys unresponsive',
    description: 'The E, R and T keys on my laptop keyboard need a hard press or do not register at all.',
    category: 'Hardware',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'CLOSED',
    ageHours: 400,
    resolveAfterHours: 48,
    assign: 2,
    csat: 5,
  },
  {
    title: 'Battery not charging past 80% and draining fast',
    description: 'Laptop battery stops charging at 80% and only lasts about an hour. Fairly new machine.',
    category: 'Hardware',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'OPEN',
    ageHours: 14,
  },
  {
    title: 'Request replacement for cracked laptop screen',
    description: 'Screen has a crack in the corner spreading across the panel. Still usable on an external monitor for now.',
    category: 'Hardware',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'IN_PROGRESS',
    ageHours: 40,
    assign: 2,
  },

  // ── Software / accounts ───────────────────────────────────────────
  {
    title: 'Need Adobe Acrobat Pro installed for contract redlining',
    description: 'Legal team needs Acrobat Pro to edit and compare contract PDFs. Reader is not enough.',
    category: 'Software',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'RESOLVED',
    ageHours: 160,
    resolveAfterHours: 20,
    assign: 1,
    csat: 4,
  },
  {
    title: 'Excel crashing when opening files from the finance share',
    description: 'Excel hangs then crashes whenever I open workbooks from the finance share. Local files are fine.',
    category: 'Software',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 90,
    resolveAfterHours: 4,
    assign: 1,
    csat: 3,
    comments: [{ staff: true, body: 'Disabled the COM add-in that was choking on files opened over SMB. Stable since.' }],
  },
  {
    title: 'Two-factor app not prompting — cannot log into portal',
    description: 'My authenticator app stopped getting push prompts so I am locked out of the SSO portal.',
    category: 'Security',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 30,
    resolveAfterHours: 1,
    assign: 4,
    csat: 5,
    actions: [{ type: 'PASSWORD_RESET', notes: 'Re-registered MFA device after identity check' }],
  },
  {
    title: 'New starter in Sales has no accounts on day one',
    description: 'New sales rep started today and has no AD account, mailbox or laptop. Manager escalated.',
    category: 'Accounts / Onboarding',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 250,
    resolveAfterHours: 6,
    assign: 0,
    csat: 2,
    comments: [{ staff: true, body: 'HR ticket arrived late. Fast-tracked account + loaner laptop. Feedback given to onboarding process.' }],
  },
  {
    title: 'Offboarding — disable accounts and collect equipment for leaver',
    description: 'Employee leaves Friday. Need accounts disabled at 5pm and a plan to collect the laptop and phone.',
    category: 'Accounts / Onboarding',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'OPEN',
    ageHours: 26,
  },
  {
    title: 'Access request — read access to the Legal contracts folder',
    description: 'I need read-only access to the Legal contracts share to review vendor agreements for procurement.',
    category: 'Storage / File Share',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'RESOLVED',
    ageHours: 110,
    resolveAfterHours: 18,
    assign: 2,
    csat: 4,
  },

  // ── Mobile / MDM ─────────────────────────────────────────────────
  {
    title: 'Corporate iPhone stuck on "Remote Management" screen after reset',
    description: 'Reset my work iPhone and now it is stuck asking for Remote Management sign-in which will not accept my password.',
    category: 'Mobile / MDM',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 70,
    resolveAfterHours: 5,
    assign: 4,
    csat: 4,
  },
  {
    title: 'Android work profile not syncing email or calendar',
    description: 'The work profile on my Android phone shows no new mail since yesterday and the calendar is blank.',
    category: 'Mobile / MDM',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'IN_PROGRESS',
    ageHours: 18,
    assign: 4,
  },
  {
    title: 'Lost phone — need remote wipe of a corporate device',
    description: 'I left my work phone in a taxi and cannot get it back. Please wipe it. It had mail and the authenticator on it.',
    category: 'Security',
    impact: 'SINGLE_USER',
    urgency: 'SYSTEM_DOWN',
    status: 'RESOLVED',
    ageHours: 200,
    resolveAfterHours: 1,
    assign: 4,
    csat: 5,
    comments: [{ staff: true, body: 'Remote wipe issued and confirmed. MFA reset. Asset marked lost pending police report.' }],
  },
  {
    title: 'MDM compliance alert — 6 devices on an out-of-date OS',
    description: 'The MDM console is flagging six enrolled devices below the minimum OS baseline. Need them chased and updated.',
    category: 'Mobile / MDM',
    impact: 'DEPARTMENT',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'OPEN',
    ageHours: 34,
  },

  // ── Telephony / Video conferencing ───────────────────────────────
  {
    title: 'Boardroom video conferencing — no camera detected before executive meeting',
    description: 'The boardroom VC system shows no camera and no microphone. There is a board meeting in an hour.',
    category: 'Telephony / VC',
    impact: 'DEPARTMENT',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 150,
    resolveAfterHours: 1,
    assign: 3,
    csat: 5,
    actions: [{ type: 'HARDWARE_SWAP', notes: 'Reseated USB host cable and replaced a failing USB extender' }],
  },
  {
    title: 'Meeting room 2B — screen share drops after a few minutes',
    description: 'Wireless screen share in room 2B disconnects every few minutes. HDMI cable works fine as a workaround.',
    category: 'Telephony / VC',
    impact: 'DEPARTMENT',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'OPEN',
    ageHours: 22,
  },
  {
    title: 'Desk phone has no dial tone after floor move',
    description: 'Moved desks and now my VoIP phone has no dial tone. The PC on the same network port works.',
    category: 'Telephony / VC',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'RESOLVED',
    ageHours: 130,
    resolveAfterHours: 4,
    assign: 3,
    csat: 4,
  },

  // ── Network / Wi-Fi ─────────────────────────────────────────────
  {
    title: 'Wi-Fi very slow in the west wing since this morning',
    description: 'Wireless in the west wing is crawling. Wired connections are fine. Started around 8am.',
    category: 'Network',
    impact: 'DEPARTMENT',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 44,
    resolveAfterHours: 3,
    assign: 3,
    csat: 4,
    comments: [{ staff: true, body: 'One AP had failed over to a congested channel. Reset it and re-ran the channel plan.' }],
  },
  {
    title: 'Cannot reach an internal web app — "site cannot be reached"',
    description: 'The internal expense app will not load for me. Colleagues on the same team can get to it.',
    category: 'Network',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 66,
    resolveAfterHours: 2,
    assign: 3,
    csat: 4,
  },
  {
    title: 'Guest Wi-Fi captive portal not appearing for visitors',
    description: 'Visitors connect to Guest Wi-Fi but the sign-in page never pops up so they get no internet.',
    category: 'Network',
    impact: 'DEPARTMENT',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'OPEN',
    ageHours: 12,
  },

  // ── Storage ─────────────────────────────────────────────────────
  {
    title: 'Department file share is full — cannot save files',
    description: 'Getting "not enough space" saving to the Supply Chain share. It is at 100% capacity.',
    category: 'Storage / File Share',
    impact: 'DEPARTMENT',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 180,
    resolveAfterHours: 5,
    assign: 2,
    csat: 4,
  },
  {
    title: 'Accidentally deleted a folder from the shared drive — need restore',
    description: 'I deleted the wrong folder from the marketing share about an hour ago. Need it restored from backup.',
    category: 'Storage / File Share',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 100,
    resolveAfterHours: 2,
    assign: 2,
    csat: 5,
  },
  {
    title: 'OneDrive stuck "processing changes" for two days',
    description: 'OneDrive sync has been stuck on processing changes for two days. Files are not backing up.',
    category: 'Software',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'OPEN',
    ageHours: 16,
  },

  // ── Misc break-fix ─────────────────────────────────────────────
  {
    title: 'Mouse and keyboard lag intermittently on desktop PC',
    description: 'My wireless keyboard and mouse freeze for a second or two every few minutes. New batteries did not help.',
    category: 'Hardware',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'RESOLVED',
    ageHours: 260,
    resolveAfterHours: 30,
    assign: 1,
    csat: 3,
  },
  {
    title: 'Second monitor flickers when the laptop is docked',
    description: 'My right-hand monitor flickers black once or twice a minute, only when docked. Undocked and on HDMI it is fine.',
    category: 'Hardware',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'OPEN',
    ageHours: 28,
  },
  {
    title: 'Teams audio not working after headset firmware update',
    description: 'After the headset app updated firmware, Teams no longer sees the headset mic or speakers.',
    category: 'Software',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 58,
    resolveAfterHours: 2,
    assign: 1,
    csat: 4,
  },
  {
    title: 'Request a docking station and a second monitor for a hybrid desk',
    description: 'I hot-desk three days a week and would like a dock and a spare monitor at the shared bench in zone C.',
    category: 'Hardware',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'RESOLVED',
    ageHours: 340,
    resolveAfterHours: 60,
    assign: 2,
    csat: 4,
  },
  {
    title: 'Password expired while travelling — cannot change it remotely',
    description: 'My password expired while I am abroad and the change-password page will not work over the VPN.',
    category: 'Active Directory',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 46,
    resolveAfterHours: 1,
    assign: 0,
    csat: 5,
    actions: [{ type: 'PASSWORD_RESET', notes: 'Reset after callback verification; walked user through remote change' }],
  },
  {
    title: 'CRM reports timing out when running the weekly pipeline export',
    description: 'The weekly pipeline export in the CRM times out at around 90 seconds every time now. It used to complete.',
    category: 'Software',
    impact: 'DEPARTMENT',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'IN_PROGRESS',
    ageHours: 36,
    assign: 1,
  },
  {
    title: 'Laptop very slow after latest OS update — high disk usage',
    description: 'Since the OS update my laptop sits at 100% disk for the first 20 minutes and is unusable until it settles.',
    category: 'Hardware',
    impact: 'SINGLE_USER',
    urgency: 'WORK_DEGRADED',
    status: 'RESOLVED',
    ageHours: 84,
    resolveAfterHours: 5,
    assign: 1,
    csat: 3,
  },
  {
    title: 'Cannot connect to the office Wi-Fi on a personal phone',
    description: 'My personal phone will not join the corporate Wi-Fi anymore — it just says "authentication error".',
    category: 'Network',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'RESOLVED',
    ageHours: 150,
    resolveAfterHours: 8,
    assign: 3,
    csat: 4,
  },
  {
    title: 'New laptop request for a returning contractor',
    description: 'A contractor is returning next month and needs a standard laptop image and a temporary account for 6 months.',
    category: 'Accounts / Onboarding',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'OPEN',
    ageHours: 20,
  },
  {
    title: 'Screen share audio not passing through in Zoom room',
    description: 'When we share a video in the Zoom room the far side sees the picture but hears no audio.',
    category: 'Telephony / VC',
    impact: 'DEPARTMENT',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'RESOLVED',
    ageHours: 175,
    resolveAfterHours: 6,
    assign: 3,
    csat: 4,
  },
  {
    title: 'Outlook search returns no results on desktop',
    description: 'Search in desktop Outlook finds nothing, even for emails I am looking straight at. Web search works.',
    category: 'Email',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'RESOLVED',
    ageHours: 62,
    resolveAfterHours: 3,
    assign: 1,
    csat: 4,
  },
  {
    title: 'Request bulk software install of design suite for 4 new designers',
    description: 'Marketing has four new designers starting in two weeks who all need the full design suite on their machines.',
    category: 'Software',
    impact: 'DEPARTMENT',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'OPEN',
    ageHours: 30,
  },
  {
    title: 'VPN client will not install on a new personal laptop',
    description: 'Setting up a new personal laptop for occasional remote work and the VPN client installer fails at the driver step.',
    category: 'VPN / Remote Access',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'RESOLVED',
    ageHours: 210,
    resolveAfterHours: 12,
    assign: 0,
    csat: 3,
  },
  {
    title: 'Conference room booking panel frozen on a black screen',
    description: 'The tablet outside meeting room 3A is frozen and will not let anyone book or check in.',
    category: 'Telephony / VC',
    impact: 'DEPARTMENT',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'RESOLVED',
    ageHours: 240,
    resolveAfterHours: 20,
    assign: 3,
    csat: 4,
  },
  {
    title: 'Shared printer missing from the print server list',
    description: 'The HR printer I usually use is no longer in the list when I add a printer from the server.',
    category: 'Printing',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'RESOLVED',
    ageHours: 118,
    resolveAfterHours: 5,
    assign: 3,
    csat: 4,
  },
  {
    title: 'Cannot open PDFs from the browser — downloads instead',
    description: 'PDF links now download instead of opening in the browser viewer. Minor but slows down my review work.',
    category: 'Software',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'CLOSED',
    ageHours: 500,
    resolveAfterHours: 40,
    assign: 1,
    csat: 5,
  },
  {
    title: 'Intermittent "network cable unplugged" on a desktop',
    description: 'A desktop in accounts keeps briefly losing its wired connection with a "cable unplugged" balloon several times a day.',
    category: 'Network',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'IN_PROGRESS',
    ageHours: 38,
    assign: 3,
  },
  {
    title: 'Request access to the shared Engineering wiki space',
    description: 'Joined the platform team this week and need edit access to the Engineering wiki space.',
    category: 'Accounts / Onboarding',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'RESOLVED',
    ageHours: 92,
    resolveAfterHours: 10,
    assign: 2,
    csat: 5,
  },
  {
    title: 'Laptop fan running constantly and getting hot',
    description: 'The fan on my laptop runs at full speed most of the day and the underside gets uncomfortably hot.',
    category: 'Hardware',
    impact: 'SINGLE_USER',
    urgency: 'WORKAROUND_AVAILABLE',
    status: 'OPEN',
    ageHours: 24,
  },
];
